language: objective-c

addons:
  sauce_connect: true
    # username: "Your Sauce Labs username" --> SAUCE_USERNAME
    # access_key: "Your Sauce Labs access key" --> SAUCE_ACCESS_KEY

install:
  - (gem update cocoapods && cd Example/ ; pod install)
  - (cd Example/TestServer && pip3 install -r requirements.txt)
  - brew install node
  - npm install -g appium  # get appium
  - npm install wd         # get appium client

before_script:
  - (cd Example/TestServer && python3 app.py)
  - appium

script:
  - xcodebuild -workspace Example/SampleApp.xcworkspace -scheme Pods-SampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - (cd Example/TestServer && python -m unittest example_app_test)
