language: objective-c
script: xcodebuild -workspace Example/SampleApp.xcworkspace -scheme Pods-SampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
install: (gem update cocoapods && cd Example/ ; pod install)
